export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SET_RULE_DETAIL = 'SET_RULE_DETAIL'
export const SET_TRIGGER_DETAIL = 'SET_TRIGGER_DETAIL'
export const SET_USER_DETAIL = 'SET_USER_DETAIL'
export const REMOVE_DETAILS = 'REMOVE_DETAILS'
export const SAVE_DETAILS = 'SAVE_DETAILS'

